Optimization:
  MaxLoop: 1000
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.6
    VelCoeff: 0.4
    powerCoeff: 0.0
    forceCoeff: 0.0
    smoothCoeff: 0.0
    ImpactCoeff: 0.0

Environment:
  Gravity: 9.8
  Friction_Coeff: 1.0
  ForceRatio: 50000

Controller:
  # Forward: False
  FrontForward: true
  HindForward: true
  # Target: 5
  Period: 5
  dt: 0.02
  # Stance: 0.26
  # Phase: [0, 0.5]
  CollectionNum: 50
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 2.0]
    dy: [-20, 20]
    Fx: [-2000, 2000]
    Fy: [0, 2000]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    # mass: [7.5, 2, 0.28, 0.5]
    # inertia: [0, 0.016, 0.01, 0.012]
    # massCenter: [0, 0.05, 0.05, 0.15]
    mass: [30, 20, 6.8, 4, 2.6]
    inertia: [0.625, 0.3, 0.14, 0.03, 0.03]
    massCenter: [0.25, 0.17, 0.22, 0.12, 0.18]
  Geometry:
    L_body: 0.5
    L_thigh: 0.42
    L_shank: 0.5
    L_arm: 0.3
    L_forearm: 0.37
  damping: 0.0
  Motor:
    MaxTorque: 1000
    MaxSpeed: 106
    CriticalSpeed: 54

  