Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.0
    powerCoeff: 0.0
    TorqueTodoCoef: 0
    forceCoeff: 0.6
    smoothCoeff: 0.2
    ImpactCoeff: 0.2

Environment:
  Gravity: 9.8
  Friction_Coeff: 1.0
  ForceRatio: 50000

Controller:
  # Forward: False
  FrontForward: true
  HindForward: true
  Target: 8
  Period: 0.49
  Stance: 0.28
  ## 2m/s
  # Period: 0.53
  # Stance: 0.45
  ## 3m/s
  # Period: 0.46
  # Stance: 0.41
  ## 4m/s
  # Period: 0.46
  # Stance: 0.37
  ## 5m/s
  # Period: 0.4
  # Stance: 0.34
  ## 6m/s
  # Period: 0.4
  # Stance: 0.35
  ## 7m/s
  # Period: 0.4
  # Stance: 0.32
  # ## 8m/s
  # Period: 0.35
  # Stance: 0.25
  ## 9m/s
  # Period: 0.35
  # Stance: 0.24
  ## 10m/s
  # Period: 0.35
  # Stance: 0.23
  Phase: [0, 0.5]
  CollectionNum: 200
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 1.0]
    dy: [-20, 20]
    Fx: [-4000, 4000]
    Fy: [0, 4000]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    # mass: [7.5, 2, 0.28, 1.0]
    # inertia: [0, 0.016, 0.01, 0.0075]
    # massCenter: [0, 0.05, 0.05, 0.1]
    mass: [30, 10, 3.2, 3.3]
    inertia: [0, 0.15, 0.06, 0.045]
    # inertia: [0, 0.15, 0.06, 0.21]
    massCenter: [0, 0.17, 0.22, 0.2]
  Geometry:
    L_body: 0
    L_thigh: 0.42
    L_shank: 0.5
    L_arm: 0.4
    # L_body: 0
    # L_thigh: 0.2
    # L_shank: 0.3
    # L_arm: 0.3
  damping: 0.0
  Motor:
    MaxTorque: 1000
    MaxSpeed: 600
    CriticalSpeed: 500
  