Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.5
    VelCoeff: 0.2
    powerCoeff: 0.0
    forceCoeff: 0.3
    smoothCoeff: 0.0
    ImpactCoeff: 0.0

Environment:
  Gravity: 9.8
  Friction_Coeff: 0.8
  ForceRatio: 50000

Controller:
  # Forward: False
  FrontForward: true
  HindForward: true
  Target: 5
  Period: 2.0
  dt: 0.001
  Stance: 0.26
  # Phase: [0, 0.5]
  CollectionNum: 500
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 2.0]
    dy: [-20, 20]
    Fx: [-4000, 4000]
    Fy: [0, 4000]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    mass: [6.8, 20, 30, 4, 2.6]
    inertia: [0.14, 0.3, 0.625, 0.03, 0.03]
    massCenter: [0.22, 0.17, 0.25, 0.12, 0.15]
  Geometry:
    L_body: 0.5
    L_thigh: 0.42
    L_shank: 0.5
    L_arm: 0.3
    L_forearm: 0.37
  damping: 0.0
  Motor:
    MaxTorque: 1000
    MaxSpeed: 600
    CriticalSpeed: 500

  