Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.6
    VelCoeff: 0.1
    powerCoeff: 0.0
    forceCoeff: 0.3
    smoothCoeff: 0.0
    ImpactCoeff: 0.0

Environment:
  Gravity: 9.8
  Friction_Coeff: 0.8
  ForceRatio: 50000

Controller:
  # Forward: False
  FrontForward: true
  HindForward: true
  Target: 5
  Period: 2.0
  dt: 0.002
  Stance: 0.26
  # Phase: [0, 0.5]
  CollectionNum: 500
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 2.0]
    dy: [-20, 20]
    Fx: [-4000, 4000]
    Fy: [0, 4000]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    mass: [15, 20, 6.8]
    inertia: [1.0125, 0.417, 0.09]
    massCenter: [0.5, 0.25, 0.2]
  Geometry:
    L_leg: 0.9
    L_body: 0.5
    L_arm: 0.4
  damping: 0.0
  Motor:
    MaxTorque: 1000
    MaxSpeed: 600
    CriticalSpeed: 500

  