Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.0
    powerCoeff: 0.0
    forceCoeff: 0.6
    smoothCoeff: 0.2
    ImpactCoeff: 0.2

Environment:
  Gravity: 9.8
  Friction_Coeff: 1.0
  ForceRatio: 50000

Controller:
  # Forward: False
  FrontForward: true
  HindForward: true
  Target: 5
  Period: 0.26
  Stance: 0.3
  Phase: [0, 0.5]
  CollectionNum: 100
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 1.0]
    dy: [-20, 20]
    Fx: [-2000, 2000]
    Fy: [0, 2000]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    # mass: [7.5, 2, 0.28, 1.0]
    # inertia: [0, 0.016, 0.01, 0.0075]
    # massCenter: [0, 0.05, 0.05, 0.1]
    mass: [30, 10, 3.2, 3.3]
    inertia: [0, 0.15, 0.06, 0.12]
    massCenter: [0, 0.17, 0.22, 0.3]
  Geometry:
    L_body: 0
    L_thigh: 0.42
    L_shank: 0.5
    L_arm: 0.67
    # L_body: 0
    # L_thigh: 0.2
    # L_shank: 0.3
    # L_arm: 0.3
  damping: 0.0
  Motor:
    MaxTorque: 1000
    MaxSpeed: 200
    CriticalSpeed: 180
  