Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    postarCoeff: 5
    powerCoeff: 0.1
    torqueCoef: 0.1

Environment:
  Gravity: 9.8
  Friction_Coeff: 1.0
  t_step: 0.001
  sim_time: 4000  

Controller:
  Target: 0.0
  dt: 0.002
  T: 0.5
  Tp: 0.08  

  Boundary:
    theta1: [-1.57, 1.57]
    theta2: [-9.42, 9.42]
    theta3: [-9.42, 9.42]


Robot:
  Mass:
    mass: [0.5, 0.2, 0.2]
    inertia: [0.0267, 0.01067, 0.01067]
    massCenter: [0.4, 0.4, 0.4]
  Geometry:
    L_body: 0.8
    L_thigh: 0.8
    L_shank: 0.8
  damping: 0.0
  Motor:
    MaxTorque: 36
    MaxSpeed: 53
    CriticalSpeed: 27
  