Optimization:
  MaxLoop: 100
  RandomSeed: 1

  CostCoef:
    postarCoef: [100, 60, 60]
    VeltarCoef: [30, 20, 20]
    # postarCoef: 100
    # VeltarCoef: 20
    torqueCoef: [5, 5]
    DtorqueCoef: [10.0, 10.0]

Environment:
  Gravity: 9.81
  Friction_Coeff: 1.0
  t_step: 0.02
  sim_time: 4000  

Controller:
  PosTar: 0.0
  VelTar: 0.0
  dt: 0.02
  T: 5.0
  Nc: 1
  Tp: 0.8

  Boundary:
    theta1: [-1.57, 1.57]
    theta2: [-20, 20]
    theta3: [-20, 20]


Robot:
  Mass:
    # inertia: [0.015, 0.006, 0.006]
    inertia: [0.035, 0.02, 0.02]
    # inertia: [0.035, 0.03, 0.03]
    mass: [0.5, 0.2, 0.2]
    # inertia: [0.367, 0.11067, 0.11067]
    massCenter: [0.4, 0.15, 0.15]
    # massCenter: [0.75, 0.2, 0.2]
  Geometry:
    L_body: 0.8
    L_thigh: 0.3
    L_shank: 0.3
    # L_body: 1.5
    # L_thigh: 0.4
    # L_shank: 0.4
  damping: 0.0
  Motor:
    MaxTorque: 100
    MaxSpeed: 100
    CriticalSpeed: 100
  