Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    postarCoeff: 100
    powerCoeff: 0.0
    torqueCoef: 0.0

Environment:
  Gravity: 9.8
  Friction_Coeff: 1.0
  t_step: 0.001
  sim_time: 4000  

Controller:
  PosTar: 0.0
  VelTar: 0.0
  dt: 0.01
  T: 2.0
  Tp: 5.0

  Boundary:
    theta1: [-1.57, 1.57]
    theta2: [-20, 20]
    theta3: [-20, 20]


Robot:
  Mass:
    mass: [0.5, 0.2, 0.2]
    inertia: [0.367, 0.11067, 0.11067]
    massCenter: [0.4, 0.3, 0.3]
  Geometry:
    L_body: 0.8
    L_thigh: 0.3
    L_shank: 0.3
  damping: 0.0
  Motor:
    MaxTorque: 36
    MaxSpeed: 100
    CriticalSpeed: 100
  