Optimization:
  MaxLoop: 500
  RandomSeed: 1

  CostCoeff:
    trackingCoeff: 0.6
    VelCoeff: 0.1
    powerCoeff: 0.0
    forceCoeff: 0.3
    smoothCoeff: 0.0
    ImpactCoeff: 0.0

Environment:
  Gravity: 9.8
  Friction_Coeff: 0.8
  ForceRatio: 50000

Controller:
  Target: 5
  Period: 0.2
  dt: 0.001
  CollectionNum: 500
  

  Boundary:
    x: [-20, 20]
    dx: [-20, 20]
    y: [0.2, 2.0]
    dy: [-20, 20]

Ref:
  delta: 0.05
  offset: 0.4
  alpha: 0.15
  beta: -200

Robot:
  Mass:
    # body, thigh, shank, arm
    mass: [1.0, 1.0]
    inertia: [0.0075, 0.0075]
    massCenter: [0.15, 0.15]
  Geometry:
    L1: 0.3
    L2: 0.3
  damping: 0.0
  Motor:
    MaxTorque: 27
    MaxSpeed: 54
    CriticalSpeed: 30

  